### Updates an existing patient entity
PUT  http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "id":  "123e4567-e89b-12d3-a456-426614174000",
  "name": "Frank Muller",
  "email": "test2@gmail.com",
  "address": "123 Main Road",
  "dateOfBirth": "1995-10-10"
}

###