spring:
  application:
    name: patient-service

    # UNCOMMENT TO USE IN MEMORY DATABASE OUTSIDE OF DOCKER
    #  spring:
    #    h2:
    #      console:
    #        path: /h2-console
    #
    #  datasource:
    #    url: jdbc:h2:mem:testdb
    #    driver-class-name: org.h2.Driver
    #    username: admin_viewer
    #    password: password
    #
    #  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    #    hibernate:
    #      ddl-auto: update
    #
    #  sql:
    #    init:
    #      mode: always

#  datasource:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/patient-service_db/db
#      username: postgres
#      password: password
#
#  jpa:
#     show-sql: true
#     open-in-view: false
#     hibernate:
#      ddl-auto: update
#     properties:
#      hibernate:
#        dialect:
#        format_sql: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

logging:
    level:
      root: INFO

server:
  port: 4000
